f=open("humansize.py")
#读取文件
c=f.read()
print(c)
#写文件
#f.write("hehehe")
#创建文件
f=open("1.txt","w")
f.write("heheda")
#重新打开
f=open("1.txt","w")
f.close()
f=open("sys.py","a")
f.write("heheda")
f.close()
f=open("sys.py","r+")
f.write("testheheda")
f.close()
f=open("sys.py","w+")
f.read()